### ISSUE TITLE
"Build Monitor" Plugin not compatible with "Build Failure Analysis" Plugin 

### ISSUE THREAD

**Issue by arpitgold** [jan-molak/jenkins-build-monitor-plugin#126]
Hi Jan,

I am trying to monitor build via build monitor plugin. It was working fine, but when I installed "Build Failure Analyzer" plugin, it is giving error. Please check the below logs for same.
I am using following versions.
Jenkins : 1.597
Build Monitor Plugin : 1.6+build.135
Build Failure Analyzer Plugin : 1.12.1 

Error Logs

``` html
<html>
	<head resURL="/static/58e58a05">
		<title>Jenkins [Jenkins]</title>
		<link rel="stylesheet" type="text/css" href="/static/58e58a05/css/style.css" />
		<link rel="stylesheet" type="text/css" href="/static/58e58a05/css/color.css" />
		<link rel="stylesheet" type="text/css" href="/static/58e58a05/css/responsive-grid.css" />
		<link rel="shortcut icon" type="image/vnd.microsoft.icon" href="/static/58e58a05/favicon.ico" />
		<script>var isRunAsTest=false; var rootURL=""; var resURL="/static/58e58a05";</script>
		<script src="/static/58e58a05/scripts/prototype.js" type="text/javascript"/>
		<script src="/static/58e58a05/scripts/behavior.js" type="text/javascript"/>
		<script src='/adjuncts/58e58a05/org/kohsuke/stapler/bind.js' type='text/javascript'/>
		<script src="/static/58e58a05/scripts/yui/yahoo/yahoo-min.js"/>
		<script src="/static/58e58a05/scripts/yui/dom/dom-min.js"/>
		<script src="/static/58e58a05/scripts/yui/event/event-min.js"/>
		<script src="/static/58e58a05/scripts/yui/animation/animation-min.js"/>
		<script src="/static/58e58a05/scripts/yui/dragdrop/dragdrop-min.js"/>
		<script src="/static/58e58a05/scripts/yui/container/container-min.js"/>
		<script src="/static/58e58a05/scripts/yui/connection/connection-min.js"/>
		<script src="/static/58e58a05/scripts/yui/datasource/datasource-min.js"/>
		<script src="/static/58e58a05/scripts/yui/autocomplete/autocomplete-min.js"/>
		<script src="/static/58e58a05/scripts/yui/menu/menu-min.js"/>
		<script src="/static/58e58a05/scripts/yui/element/element-min.js"/>
		<script src="/static/58e58a05/scripts/yui/button/button-min.js"/>
		<script src="/static/58e58a05/scripts/yui/storage/storage-min.js"/>
		<script src="/static/58e58a05/scripts/hudson-behavior.js" type="text/javascript"/>
		<script src="/static/58e58a05/scripts/sortable.js" type="text/javascript"/>
		<script>crumb.init("", "");</script>
		<link rel="stylesheet" type="text/css" href="/static/58e58a05/scripts/yui/container/assets/container.css" />
		<link rel="stylesheet" type="text/css" href="/static/58e58a05/scripts/yui/assets/skins/sam/skin.css" />
		<link rel="stylesheet" type="text/css" href="/static/58e58a05/scripts/yui/container/assets/skins/sam/container.css" />
		<link rel="stylesheet" type="text/css" href="/static/58e58a05/scripts/yui/button/assets/skins/sam/button.css" />
		<link rel="stylesheet" type="text/css" href="/static/58e58a05/scripts/yui/menu/assets/skins/sam/menu.css" />
		<meta name="ROBOTS" content="INDEX,NOFOLLOW" />
		<script src="/adjuncts/58e58a05/org/kohsuke/stapler/jquery/jquery.full.js" type="text/javascript"/>
		<script>var Q=jQuery.noConflict()</script>
		<link rel="stylesheet" type="text/css" href="/static/58e58a05/plugin/sectioned-view/sectioned-view.css" />
		<link rel="stylesheet" type="text/css" href="" />
		<script src="" type="text/javascript"/>
		<script src="/static/58e58a05/scripts/yui/cookie/cookie-min.js"/>
	</head>
	<body id="jenkins" data-version="jenkins-1.597" class="yui-skin-sam jenkins-1.597">
		<a href="#skip2content" class="skiplink">Skip to content</a>
		<div id="header">
			<div class="logo">
				<a id="jenkins-home-link" href="/">
					<img id="jenkins-head-icon" alt="title" src="/static/58e58a05/images/headshot.png" />
					<img id="jenkins-name-icon" height="34" alt="title" width="139" src="/static/58e58a05/images/title.png" />
				</a>
			</div>
			<div class="login"> <a href="/login?from=%2F%24stapler%2Fbound%2Fb515ee2a-31cf-4f84-8f2c-ba8260a938cf%2FfetchJobViews">
					<b>log in</b>
				</a>
			</div>
			<div class="searchbox hidden-xs">
				<form style="position:relative;" name="search" action="/search/" class="no-json" method="get">
					<div id="search-box-minWidth"/>
					<div id="search-box-sizer"/>
					<div id="searchform">
						<input id="search-box" placeholder="search" name="q" class="has-default-text" /> <a href="http://wiki.jenkins-ci.org/display/JENKINS/Search+Box">
							<img style="width: 16px; height: 16px; " class="icon-help icon-sm" src="/static/58e58a05/images/16x16/help.png" />
						</a>
						<div id="search-box-completion"/>
						<script>createSearchBox("/search/");</script>
					</div>
				</form>
			</div>
		</div>
		<div id="breadcrumbBar">
			<tr id="top-nav">
				<td id="left-top-nav" colspan="2">
					<link rel='stylesheet' href='/adjuncts/58e58a05/lib/layout/breadcrumbs.css' type='text/css' />
					<script src='/adjuncts/58e58a05/lib/layout/breadcrumbs.js' type='text/javascript'/>
					<div class="top-sticker noedge">
						<div class="top-sticker-inner">
							<div id="right-top-nav"/>
							<ul id="breadcrumbs">
								<li class="item">
									<a class="model-link inside" href="/">Jenkins</a>
								</li>
								<li class="children" href="/"/>
							</ul>
							<div id="breadcrumb-menu-target"/>
						</div>
					</div>
				</td>
			</tr>
		</div>
		<div id="page-body">
			<div class="row">
				<div id="side-panel">
					<div id="side-panel-content">
						<div class="task">
							<a class="task-icon-link" href="http://jenkins-ci.org/">
								<img style="width: 24px; height: 24px; width: 24px; height: 24px; margin: 2px;" class="icon-next icon-md" src="/static/58e58a05/images/24x24/next.png" />
							</a> <a class="task-link" href="http://jenkins-ci.org/">Jenkins project</a>
						</div>
						<div class="task">
							<a class="task-icon-link" href="http://issues.jenkins-ci.org/">
								<img style="width: 24px; height: 24px; width: 24px; height: 24px; margin: 2px;" class="icon-gear2 icon-md" src="/static/58e58a05/images/24x24/gear2.png" />
							</a> <a class="task-link" href="http://issues.jenkins-ci.org/">Bug tracker</a>
						</div>
						<div class="task">
							<a class="task-icon-link" href="http://jenkins-ci.org/content/mailing-lists">
								<img style="width: 24px; height: 24px; width: 24px; height: 24px; margin: 2px;" class="icon-search icon-md" src="/static/58e58a05/images/24x24/search.png" />
							</a> <a class="task-link" href="http://jenkins-ci.org/content/mailing-lists">Mailing Lists</a>
						</div>
						<div class="task">
							<a class="task-icon-link" href="https://twitter.com/jenkinsci">
								<img style="width: 24px; height: 24px; width: 24px; height: 24px; margin: 2px;" class="icon-user icon-md" src="/static/58e58a05/images/24x24/user.png" />
							</a> <a class="task-link" href="https://twitter.com/jenkinsci">Twitter: @jenkinsci</a>
						</div>
					</div>
				</div>
				<div id="main-panel">
					<div id="main-panel-content">
						<a name="skip2content"/>
						<h1 style="text-align: center">
							<img height="179" width="154" src="/static/58e58a05/images/rage.png" />
							<span style="font-size:50px"> Oops!</span>
						</h1>
						<div id="error-description">
							<p>A problem occurred while processing the request.
        Please check <a href="https://issues.jenkins-ci.org/">our bug tracker</a> to see if a similar problem has already been reported.
        If it is already reported, please vote and put a comment on it to let us gauge the impact of the problem.
        If you think this is a new issue, please file a new issue.
        When you file an issue, make sure to add the entire stack trace, along with the version of Jenkins and relevant plugins.
        <a href="http://jenkins-ci.org/content/mailing-lists">The users list</a> might be also useful in understanding what has happened.</p>
	<h2>Stack trace</h2>
	<pre style="margin:2em; clear:both">javax.servlet.ServletException: java.lang.NoClassDefFoundError: com/sonyericsson/jenkins/plugins/bfa/model/FailureCauseBuildAction
	at org.kohsuke.stapler.Stapler.tryInvoke(Stapler.java:796)
	at org.kohsuke.stapler.Stapler.invoke(Stapler.java:876)
	at org.kohsuke.stapler.MetaClass$12.dispatch(MetaClass.java:391)
	at org.kohsuke.stapler.Stapler.tryInvoke(Stapler.java:746)
	at org.kohsuke.stapler.Stapler.invoke(Stapler.java:876)
	at org.kohsuke.stapler.Stapler.tryInvoke(Stapler.java:813)
	at org.kohsuke.stapler.Stapler.invoke(Stapler.java:876)
	at org.kohsuke.stapler.Stapler.invoke(Stapler.java:649)
	at org.kohsuke.stapler.Stapler.service(Stapler.java:199)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:848)
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:686)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1494)
	at hudson.util.PluginServletFilter$1.doFilter(PluginServletFilter.java:123)
	at com.smartcodeltd.jenkinsci.plugin.assetbundler.filters.LessCSS.doFilter(LessCSS.java:43)
	at hudson.util.PluginServletFilter$1.doFilter(PluginServletFilter.java:120)
	at net.bull.javamelody.MonitoringFilter.doFilter(MonitoringFilter.java:198)
	at net.bull.javamelody.MonitoringFilter.doFilter(MonitoringFilter.java:176)
	at net.bull.javamelody.PluginMonitoringFilter.doFilter(PluginMonitoringFilter.java:85)
	at org.jvnet.hudson.plugins.monitoring.HudsonMonitoringFilter.doFilter(HudsonMonitoringFilter.java:99)
	at hudson.util.PluginServletFilter$1.doFilter(PluginServletFilter.java:120)
	at hudson.plugins.greenballs.GreenBallFilter.doFilter(GreenBallFilter.java:58)
	at hudson.util.PluginServletFilter$1.doFilter(PluginServletFilter.java:120)
	at hudson.util.PluginServletFilter.doFilter(PluginServletFilter.java:114)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1482)
	at hudson.security.csrf.CrumbFilter.doFilter(CrumbFilter.java:48)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1482)
	at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:84)
	at hudson.security.UnwrapSecurityExceptionFilter.doFilter(UnwrapSecurityExceptionFilter.java:51)
	at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:87)
	at jenkins.security.ExceptionTranslationFilter.doFilter(ExceptionTranslationFilter.java:117)
	at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:87)
	at org.acegisecurity.providers.anonymous.AnonymousProcessingFilter.doFilter(AnonymousProcessingFilter.java:125)
	at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:87)
	at org.acegisecurity.ui.rememberme.RememberMeProcessingFilter.doFilter(RememberMeProcessingFilter.java:142)
	at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:87)
	at org.acegisecurity.ui.AbstractProcessingFilter.doFilter(AbstractProcessingFilter.java:271)
	at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:87)
	at jenkins.security.BasicHeaderProcessor.doFilter(BasicHeaderProcessor.java:93)
	at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:87)
	at org.acegisecurity.context.HttpSessionContextIntegrationFilter.doFilter(HttpSessionContextIntegrationFilter.java:249)
	at hudson.security.HttpSessionContextIntegrationFilter2.doFilter(HttpSessionContextIntegrationFilter2.java:67)
	at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:87)
	at hudson.security.ChainedServletFilter.doFilter(ChainedServletFilter.java:76)
	at hudson.security.HudsonFilter.doFilter(HudsonFilter.java:164)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1482)
	at org.kohsuke.stapler.compression.CompressionFilter.doFilter(CompressionFilter.java:49)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1482)
	at hudson.util.CharacterEncodingFilter.doFilter(CharacterEncodingFilter.java:81)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1482)
	at org.kohsuke.stapler.DiagnosticThreadNameFilter.doFilter(DiagnosticThreadNameFilter.java:30)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1474)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:499)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:137)
	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:533)
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:231)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1086)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:428)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:193)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1020)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:135)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:116)
	at org.eclipse.jetty.server.Server.handle(Server.java:370)
	at org.eclipse.jetty.server.AbstractHttpConnection.handleRequest(AbstractHttpConnection.java:489)
	at org.eclipse.jetty.server.AbstractHttpConnection.content(AbstractHttpConnection.java:960)
	at org.eclipse.jetty.server.AbstractHttpConnection$RequestHandler.content(AbstractHttpConnection.java:1021)
	at org.eclipse.jetty.http.HttpParser.parseNext(HttpParser.java:865)
	at org.eclipse.jetty.http.HttpParser.parseAvailable(HttpParser.java:240)
	at org.eclipse.jetty.server.AsyncHttpConnection.handle(AsyncHttpConnection.java:82)
	at org.eclipse.jetty.io.nio.SelectChannelEndPoint.handle(SelectChannelEndPoint.java:668)
	at org.eclipse.jetty.io.nio.SelectChannelEndPoint$1.run(SelectChannelEndPoint.java:52)
	at winstone.BoundedExecutorService$1.run(BoundedExecutorService.java:77)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.NoClassDefFoundError: com/sonyericsson/jenkins/plugins/bfa/model/FailureCauseBuildAction
	at com.smartcodeltd.jenkinsci.plugins.buildmonitor.viewmodel.plugins.BuildAugmentor.detailsOfAnalysis(BuildAugmentor.java:69)
	at com.smartcodeltd.jenkinsci.plugins.buildmonitor.viewmodel.plugins.BuildAugmentor.detailsOf(BuildAugmentor.java:48)
	at com.smartcodeltd.jenkinsci.plugins.buildmonitor.viewmodel.BuildView.analysis(BuildView.java:157)
	at com.smartcodeltd.jenkinsci.plugins.buildmonitor.viewmodel.BuildView.hasKnownFailures(BuildView.java:148)
	at com.smartcodeltd.jenkinsci.plugins.buildmonitor.viewmodel.JobView.hasKnownFailures(JobView.java:151)
	at sun.reflect.GeneratedMethodAccessor1190.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.codehaus.jackson.map.ser.BeanPropertyWriter.get(BeanPropertyWriter.java:483)
	at org.codehaus.jackson.map.ser.BeanPropertyWriter.serializeAsField(BeanPropertyWriter.java:418)
	at org.codehaus.jackson.map.ser.std.BeanSerializerBase.serializeFields(BeanSerializerBase.java:150)
	at org.codehaus.jackson.map.ser.BeanSerializer.serialize(BeanSerializer.java:112)
	at org.codehaus.jackson.map.ser.std.StdContainerSerializers$IndexedListSerializer.serializeContents(StdContainerSerializers.java:122)
	at org.codehaus.jackson.map.ser.std.StdContainerSerializers$IndexedListSerializer.serializeContents(StdContainerSerializers.java:71)
	at org.codehaus.jackson.map.ser.std.AsArraySerializerBase.serialize(AsArraySerializerBase.java:86)
	at org.codehaus.jackson.map.ser.StdSerializerProvider._serializeValue(StdSerializerProvider.java:610)
	at org.codehaus.jackson.map.ser.StdSerializerProvider.serializeValue(StdSerializerProvider.java:256)
	at org.codehaus.jackson.map.ObjectMapper._configAndWriteValue(ObjectMapper.java:2575)
	at org.codehaus.jackson.map.ObjectMapper.writeValueAsString(ObjectMapper.java:2097)
	at com.smartcodeltd.jenkinsci.plugins.buildmonitor.BuildMonitorView.jsonFrom(BuildMonitorView.java:150)
	at com.smartcodeltd.jenkinsci.plugins.buildmonitor.BuildMonitorView.fetchJobViews(BuildMonitorView.java:139)
	at sun.reflect.GeneratedMethodAccessor1205.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.kohsuke.stapler.Function$InstanceFunction.invoke(Function.java:298)
	at org.kohsuke.stapler.Function.bindAndInvoke(Function.java:161)
	at org.kohsuke.stapler.Function.bindAndInvokeAndServeResponse(Function.java:96)
	at org.kohsuke.stapler.MetaClass$JavaScriptProxyMethodDispatcher.doDispatch(MetaClass.java:470)
	at org.kohsuke.stapler.NameBasedDispatcher.dispatch(NameBasedDispatcher.java:53)
	at org.kohsuke.stapler.Stapler.tryInvoke(Stapler.java:746)
	... 73 more</pre>
						</div>
					</div>
				</div>
			</div>
		</div>
		<div id="footer-container" class="hidden-xs">
			<div id="footer">
				<span class="page_generated">Page generated: Jan 22, 2015 9:20:23 AM</span>
				<span class="rest_api">
					<a href="api/">REST API</a>
				</span>
				<span class="jenkins_ver">
					<a href="http://jenkins-ci.org/">Jenkins ver. 1.597</a>
				</span>
			</div>
		</div>
	</body>
</html>
```

![capture](https://cloud.githubusercontent.com/assets/5267739/5851610/b2221f40-a22f-11e4-87e3-02946096b13f.PNG)

Please let me know, if you need any additional information.

**Comment by jan-molak** [comment]
Interesting! Thanks @arpitgold, I'll have a look!

The error message complains about:
```
java.lang.NoClassDefFoundError: com/sonyericsson/jenkins/plugins/bfa/model/FailureCauseBuildAction
```
But the class seems to be there in the Build Failure Analyzer:
[com.sonyericsson.jenkins.plugins.bfa.model.FailureCauseBuildAction](https://github.com/jenkinsci/build-failure-analyzer-plugin/blob/master/src/main/java/com/sonyericsson/jenkins/plugins/bfa/model/FailureCauseBuildAction.java)
...

**Comment by arpitgold** [comment]
Thanks jan for looking into it.
Please get me involved, if you need any additional information.

**Comment by karisivo** [comment]
Any news about this?
We have same problem with almost same revisions
Jenkins : 1.598
Build Monitor Plugin : 1.6+build.138
Build Failure Analyzer Plugin : 1.12.1 

Problems starts after Build Failure Analyzer Plugin was installed. Earlier we had own modifications of BFA plugin, but in some Jenkins update it start printing those failures and we uninstall it. I think we install same time that Build Monitoring plugin, so it seems this BFA works well wihtout this Build Monitor Plugin and have problems when both are installed.

**Comment by arpitgold** [comment]
Hi Jan, any updates on this ??

**Comment by arpitgold** [comment]
Hi Jan, any updates on this ??

**Comment by jan-molak** [comment]
I'm on holidays with very limited access to the Internet. I'll have a look
into this issue when I'm back in about two weeks.

From the initial investigation I've done it seems that the problem is
caused not by the BFA or the Build Monitor themselves, but by the changes
introduced recently in the Jenkins core (sorry, I don't have their Jira
ticket number at hand).

If you have recently upgraded your Jenkins installation, perhaps you could
try downgrading it to one of the latest Long Term Support (a.k.a. "stable")
versions?

Please let me know if this helps.

Best,
Jan

On Tuesday, 24 March 2015, Arpit Nagar <notifications@github.com> wrote:

> Hi Jan, any updates on this ??
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jan-molak/jenkins-build-monitor-plugin/issues/126#issuecomment-85475557>
> .
>


-- 
t: @JanMolak <https://twitter.com/JanMolak>
l: linkedin.com/in/janmolak <http://www.linkedin.com/in/janmolak>
g: github.com/jan-molak
w: smartcodeltd.co.uk

**Comment by jan-molak** [comment]
**Update:** Recent changes in Jenkins.

It looks like the recent changes in Jenkins did not affect the Build Monitor itself, but they did affect its dependencies, which results in what you guys have observed.

As of Jenkins 1.561 `hudson.matrix` package lives in its own plugin, and version 1.577 kicked out the `hudson.tasks.junit`. Those changes break the Claim plugin unless you install the [JUnit](https://wiki.jenkins-ci.org/display/JENKINS/JUnit+Plugin) and [Matrix Project](https://wiki.jenkins-ci.org/display/JENKINS/Matrix+Project+Plugin) plugins explicitly with it.

I've just proposed [a pull request addressing this issue](https://github.com/jenkinsci/claim-plugin/pull/16), so please vote on it :+1: and hopefully @ki82 merges it in :-)

---

That's for the Claim plugin, but I'm guessing that the issue with the Build Failure Analyzer reported by @arpitgold is related. Stay tuned!

**Comment by jan-molak** [comment]
It looks to me that the BFA class in question:
```
java.lang.NoClassDefFoundError: com/sonyericsson/jenkins/plugins/bfa/model/FailureCauseBuildAction
```
also depends on the `hudson.matrix` package. 

@arpitgold @karisivo, could you please confirm if you have the [Matrix Project plugin](https://wiki.jenkins-ci.org/display/JENKINS/Matrix+Project+Plugin) installed?

Thanks!
Jan

**Comment by mildju** [comment]
Philippe Lambert will be out of the office starting  03/04/2015 and will be
returning on 13/04/2015.

Hello,

I'm currently out of the office.  Your mail won't be forwarded but I will
respond to your message as soon as I'll be back.

For urgent matters related to the new CmaX GUI, please check with St�phane
Jantzen.
For urgent matters related to the Testing Tool, please check with Pierre
Hoffmann.

Cheers,
Philippe

----------------------------------------------------------------------------

Clearstream Services S.A.
42 Avenue JF Kennedy, L-1855 Luxembourg
Soci�t� anonyme is organised with limited liability
in the Grand Duchy of Luxembourg R.C.S. Luxembourg B 60911.

-----------------------------------------
Visit us at http://www.clearstream.com

IMPORTANT MESSAGE

Internet communications are not secure and therefore Clearstream International does not accept legal responsibility for the contents of this message.

The information contained in this e-mail is confidential and may be legally privileged. It is intended solely for the addressee. If you are not the intended recipient, any disclosure, copying, distribution or any action taken or omitted to be taken in reliance on it, is prohibited and may be unlawful. Any views expressed in this e-mail are those of the individual sender, except where the sender specifically states them to be the views of Clearstream International or of any of its affiliates or subsidiaries.

Legally required information for business correspondence/
Gesetzliche Pflichtangaben fuer Geschaeftskorrespondenz:
http://deutsche-boerse.com/letterhead

END OF DISCLAIMER

**Comment by arpitgold** [comment]
Hi Jan,

I checked both these 3 plugins, they are already installed. There version details are as follows :
Claim plugin : version 2.6
Matrix Project Plugin : version 1.4
JUnit Plugin : version 1.5 

Thanks for looking into the issue. 
Please let me know if you need more details.

**Comment by arpitgold** [comment]
Updated version of Claim plugin to 2.6 solved. 
T

**Comment by jan-molak** [comment]
Excellent, I'm glad to hear that! Thanks for letting me know! :smiley:
