### ISSUE TITLE
Failed to clean up temp dirs

### ISSUE THREAD

**Issue by RZhou94** [jan-molak/jenkins-build-monitor-plugin#142]
I am using windows 8 to compile this plugin,

And I have an IOException with this plugin of jenkins, version 1.532

java.io.IOException: Failed to clean up temp dirs
	at org.jvnet.hudson.test.TemporaryDirectoryAllocator.dispose(TemporaryDirectoryAllocator.java:86)
	at org.jvnet.hudson.test.TestEnvironment.dispose(TestEnvironment.java:81)
	at org.jvnet.hudson.test.JenkinsRule.after(JenkinsRule.java:447)
	at org.jvnet.hudson.test.JenkinsRule$2.evaluate(JenkinsRule.java:502)
	at org.junit.rules.TestWatcher$1.evaluate(TestWatcher.java:55)
	at org.junit.rules.TestWatcher$1.evaluate(TestWatcher.java:55)
	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:271)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:70)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:50)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:238)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:63)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:236)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:53)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:229)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:309)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:50)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:459)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:675)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:382)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:192)
Caused by: java.io.IOException: Unable to delete C:\Temp\hudson6847998870307798174test\plugins\ant\WEB-INF\lib\classes.jar
	at hudson.Util.deleteFile(Util.java:263)
	at hudson.Util.deleteRecursive(Util.java:310)
	at hudson.Util.deleteContentsRecursive(Util.java:212)
	at hudson.Util.deleteRecursive(Util.java:301)
	at hudson.Util.deleteContentsRecursive(Util.java:212)
	at hudson.Util.deleteRecursive(Util.java:301)
	at hudson.Util.deleteContentsRecursive(Util.java:212)
	at hudson.Util.deleteRecursive(Util.java:301)
	at hudson.Util.deleteContentsRecursive(Util.java:212)
	at hudson.Util.deleteRecursive(Util.java:301)
	at hudson.Util.deleteContentsRecursive(Util.java:212)
	at hudson.Util.deleteRecursive(Util.java:301)
	at hudson.FilePath$12.invoke(FilePath.java:1095)
	at hudson.FilePath$12.invoke(FilePath.java:1092)
	at hudson.FilePath.act(FilePath.java:918)
	at hudson.FilePath.act(FilePath.java:896)
	at hudson.FilePath.deleteRecursive(FilePath.java:1092)
	at org.jvnet.hudson.test.TemporaryDirectoryAllocator.dispose(TemporaryDirectoryAllocator.java:81)
	... 21 more

I found on jenkins changelog, with 1.579 this bug is fixed, 
http://jenkins-ci.org/changelog

Well i am trying to change this dependancy.

Should I do it, or this is already solved?

**Comment by jan-molak** [comment]
It's a bug in Jenkins not in the Build Monitor; If you'd like to develop on Windows 8 you can change your dependency on Jenkins core to 1.579, but the changes should still be verified against Jenkins Core 1.532 as that's the earliest Long Term Support release covering at least 80% of Jenkins installations.
